-- phpMyAdmin SQL Dump
-- version 5.1.0
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Jun 12, 2021 at 11:02 AM
-- Server version: 10.4.18-MariaDB
-- PHP Version: 8.0.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `urbanbasket`
--

-- --------------------------------------------------------

--
-- Table structure for table `mobile`
--

CREATE TABLE `mobile` (
  `item_id` int(11) NOT NULL,
  `item_brand` varchar(200) NOT NULL,
  `item_name` varchar(255) NOT NULL,
  `item_price` double(10,2) NOT NULL,
  `item_image` varchar(255) NOT NULL,
  `section_id` int(11) DEFAULT NULL,
  `item_qty` int(11) DEFAULT 100,
  `item_descr` text DEFAULT 'lorem40',
  `item_datetime` datetime DEFAULT current_timestamp(),
  `item_type` varchar(40) DEFAULT 'mobile'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Dumping data for table `mobile`
--

INSERT INTO `mobile` (`item_id`, `item_brand`, `item_name`, `item_price`, `item_image`, `section_id`, `item_qty`, `item_descr`, `item_datetime`, `item_type`) VALUES
(1, 'Apple', 'iPhone 12 mini(64GB)', 59999.00, 'images/MOBILE/iphone12mini.jpg', 1, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(2, 'Redmi', 'Redmi Note 9(128GB)', 14595.00, 'images/MOBILE/redminote9.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(3, 'OPPO', 'Reno 4 Pro', 34990.00, 'images/MOBILE/opporeno4.jpg', 1, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(4, 'Samsung', 'Galaxy S21(64GB)', 105990.00, 'images/MOBILE/samsungs21.jpg', 3, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(5, 'Oneplus', 'Oneplus 8', 41990.00, 'images/MOBILE/oneplus8.jpg', 3, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(6, 'Oneplus', 'Oneplus Nord', 27999.00, 'images/MOBILE/oneplusnord.jpg', 3, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(7, 'Apple', 'iPhone 11', 48999.00, 'images/slider2-1.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(8, 'Oneplus', 'Oneplus 8 pro', 54999.00, 'images/MOBILE/oneplus8pro.jpg', 1, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(9, 'Samsung', 'Galaxy Z Flip', 84999.00, 'images/MOBILE/samsunggalaxyzflip.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(10, 'Samsung', 'Note 20 Ultra', 104990.00, 'images/MOBILE/samsungnote20.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(11, 'Samsung', 'Galaxy Z Fold 2', 149998.00, 'images/MOBILE/samsungzfold.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(12, 'Samsung', 'Galaxy M21', 12499.00, 'images/MOBILE/samsungm21.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(13, 'Oppo', 'F17 Pro(128GB)', 21490.00, 'images/MOBILE/oppof17pro.jpg', 2, 100, 'lorem40', '2021-05-18 21:45:57', 'mobile'),
(14, 'Redmi', 'Mi 10 ', 49990.00, 'images/MOBILE/mi10.jpg', 2, 100, 'lorem40', '2021-05-20 19:38:57', 'mobile'),
(15, 'Oneplus', 'Oneplus 8T', 42999.00, 'images/MOBILE/oneplus8t.jpg', 2, 100, 'lorem40', '2021-05-20 19:38:57', 'mobile'),
(16, 'Apple', 'iPhone 12 Pro Max', 45999.00, 'images/MOBILE/iphone12promax.jpg', 2, 100, 'lorem40', '2021-05-20 21:34:11', 'mobile'),
(17, 'Apple', 'iphone xr', 39999.00, 'images/MOBILE/iphonexr.jpg', 2, 100, 'lorem40', '2021-05-20 21:34:11', 'mobile'),
(20, 'Apple', 'iPhone 12 mini(128GB)', 74990.00, 'images/MOBILE/i12mini.jpg', 1, 100, 'Specification: 128 GB ROM, \r\n13.72 cm (5.4 inch) Super Retina XDR Display, \r\n12MP + 12MP | 12MP Front Camera\r\n, A14 Bionic Chip with Next Generation Neural Engine Processor\r\nCeramic Shield\r\n, IP68 Water Resistance\r\n, All Screen OLED Display', '2021-05-21 23:58:44', 'mobile'),
(22, 'Oneplus', 'Oneplus 9 5G(Winter Mist, 256GB)(12GB RAM)', 54999.00, 'images/MOBILE/oneplus9.jpg', 3, 100, 'Specification: 12 GB RAM | 256 GB ROM | ,\r\n, 16.26 cm(6.5 inch) AMOLED Display\r\n, 48MP + 50MP + monochrome lens | 5MP Front Camera\r\n, 3000 mAh Battery\r\n, Snapdragon 888 CPU', '2021-05-22 00:07:27', 'mobile'),
(23, 'Redmi', 'Mi 11X pro(Celestial Silver,128GB Storage)(8GB RAM)', 47999.00, 'images/MOBILE/mi11xpro.jpg', 3, 100, 'Specification: Celestial Silver, | 8GB RAM |, | 128GB |, Qualcomm Snapdragon 888 5G with Kryo 680 Octa-core, 5nm process, Up to 2.84GHz clock speed, Liquid cool technology, \r\nCamera: 108 MP Triple Rear camera with 8MP Ultra-wide and 5MP Super macro | 20 MP Front camera |, \r\nDisplay: 120Hz high refresh rate FHD+ (1080x2400) AMOLED Dot display; 16.9 centimeters (6.67 inch) HDR 10+ support,  360Hz touch sampling, MEMC technology\r\nBattery: 4520 mAH large battery with 33W fast charger in-box and Type-C connectivity\r\nMemory, Storage & SIM: 8GB LPDDR5 RAM | 128GB UFS 3.1 storage', '2021-05-22 00:44:14', 'mobile'),
(24, 'Samsung', 'Samsung Galaxy A72(Violet, 128GB)( 8GB RAM)', 41999.00, 'images/MOBILE/galaxya72.jpg', 2, 100, 'Specification: Violet, | 8GB RAM |, | 128GB |, 64MP+12MP+8MP+5MP Quad camera |, 32MP (F2.2) front camera, \r\n16.95 centimeters (6.7-inch) FHD+ Super AMOLED Plus- infinity O display, 90hz refresh rate, FHD+ resolution with 1080 x 2400 (FHD+) pixls , 407 PPI with 16M colours, | Dual SIM (nano+nano) dual-standby (4G+4G) |\r\nAndroid 11, v11.0 operating system,  SDM720G octa core processor\r\n5000mAH lithium-ion battery, with 25w fast charging, 1 year manufacturer warranty for device and 6 months manufacturer warranty for in-box accessories including batteries from the date of purchase', '2021-05-22 00:44:14', 'mobile'),
(25, 'OPPO', 'OPPO Reno5 Pro 5G(Astral Blue, 128GB)(8GB RAM)', 38990.00, 'images/MOBILE/opporeno5.jpeg', 2, 100, 'Specification: Astral Blue, | 128GB |, | 8GB RAM |, 3D Borderless Sense Screen, AI Highlight Video (Ultra Night Video + Live HDR), Super AMOLED Display, \r\n64MP + 8MP + 2MP + 2MP, 32MP Front Camera, \r\nInnovative 65W SuperVOOC 2.0 flash charging brings the 4350 mAh battery, 5 minutes charging & 4hours of video playback, fully charging in 30 minutes, \r\n16.64 cm (6.55 inch) Full HD+ Display with 2400x1080 resolution, \r\nColor OS 11.1 based on Android v11.0, OS with 2.6GHz, MediaTek (MT6889) Processor, ARM G77 MC9 836 MHz', '2021-05-22 01:21:34', 'mobile'),
(26, 'OPPO', 'OPPO FIND X2(Black, 256GB)(12GB RAM)', 54990.00, 'images/MOBILE/oppofindx2.jpg', 1, 100, 'Specification: Black, | 12GB RAM |, | 256GB |, 48MP (Sony IMX586 Sensor) wide-angle lens (f/1.7 aperture) rear camera, 12MP (Sony IMX708 Sensor) ultra-wide-angle lens (f/2.2 aperture), 13MP (f/2.4 aperture) telephoto camera | 32MP front facing camera, \r\n17.01 centimeters (6.7-inch) OLED curved screen with 120Hz ultra-high refresh rate, QHD+ display 3168 x 1440 pixels resolution, 513 ppi pixel density, \r\nColor OS 7.1 based on Android v10.0 operating system with 2.8GHz Qualcomm Snapdragon 865 octa core processor, Adreno 650 GPU', '2021-05-22 01:21:34', 'mobile'),
(27, 'Apple', 'Apple 5W USB Power Adapter', 1700.00, 'images/MOBILE/apple5w.jpeg', 11, 100, 'Specification: Featuring an ultracompact design, this power adapter offers fast, efficient charging at home, in the office, or on the go\r\nWorks with any iPhone, Apple Watch, iPad or iPod model\r\nImportant note: This USB Power Adapter has fixed prongs for use in the India\r\nCharging cable sold separately', '2021-05-22 01:43:27', 'accessories'),
(28, 'boAt', 'boAt Rockerz 255 Pro(Teal Green)', 1999.00, 'images/MOBILE/boAtRockerzz.jpeg', 10, 100, 'Specification: Battery: Rockerz 255 Pro offers a playback time of up to 10 hours and gets charged to 100% in 1 hour, \r\nBluetooth: It has Bluetooth v5.0 with a range of 10m and is compatible with Android & iOS, \r\nIPX rating: It has an IPX5 marked water & sweat resistance., \r\nANC: NA, \r\nNo. of Mic: 1, \r\nOther Inclusions: Additional Earmuffs, Micro USB Charging Cable, Warranty Card, User Manual, \r\nSports friendly design with Easy Controls, \r\nInstant Voice Assistant, \r\nDrivers: 10mm Drivers with boAt, Signature Sound, \r\n1 year warranty from the date of purchase', '2021-05-22 01:43:27', 'accessories'),
(29, 'Staples', 'Aashirvaad Atta/Godihittu - Whole Wheat, 10 kg', 490.00, 'images/FOOD/fooditems/ashrvdatta10kg.webp', 5, 100, 'Aashirvaad whole wheat atta is made of zero per cent maida and 100% atta, which makes it extremely nutritious since its packed with health benefits. This also means more fluffy and soft rotis at home. Aashirvaad Atta is also made from the best grains - heavy on the palm, golden amber in colour and hard in bite. It is grounded using the chakki - grinding process for the perfect balance of colour, taste and nutrition.\r\n || • Whole wheat atta is comparatively healthier than bleached white flour, which is obtained after processing and 60% extraction from grain. If you are consuming whole wheat atta, you are eating food enriched with vitamin B1, B3, B2, folic acid, calcium, phosphorus, iron, fiber and zinc. • Many health disorders, which are integrally linked with nourishment like mineral deficiencies, pregnancy problems, obesity, anaemia, chronic inflammation are cured by consuming whole wheat.', '2021-05-22 14:36:44', 'food'),
(30, 'Staples', 'Tata Sampann Toor Dal/Togari Bele, 1 Kg Pouch', 189.00, 'images/FOOD/fooditems/tatatoordal1kg.webp', 5, 100, 'For most Indians, comfort food is always linked to easy-to-cook homemade meals and what can be the most convenient and quick to prepare dal. A staple in the Indian diet, Toor dal is rich in protein and can be enjoyed well with Rotis or rice. It can be used to prepare sambar, dal tadka, the Maharashtrian varan, and more. Tata Sampann Toor dal is unpolished as it does not undergo any artificial polishing with water, oil, or leather thereby retaining its goodness and wholesomeness. The 5-step process ensures that Tata Sampann Toor dal grains are uniform and of premium quality, giving you an all-natural, authentic taste. So, whenever you are in the mood to cook something easy and delicious, dive into the scrumptious taste of Tata Sampann pulses, and enjoy a lovely meal! ||\r\n\r\nExplore Tata Sampann Pulses range - Toor dal, Chana dal, Moong dal, Moong dal Chilka, Green Moong, Masoor dal, Masoor Small dal, Masoor Whole dal, Kali Masoor dal, Urad dal, Urad Whole dal, Urad Kali, Chawli (Lobia), Kabuli Chana, Kala Chana, Matki (Moth bean) and Rajma. ||\r\n\r\nAlso Try: Try chana dal, urad dal, moong dal, masoor dal, Kabuli chana, etc.', '2021-05-22 14:51:36', 'food'),
(31, 'Staples', 'Tata Sampann Urad Dal/Uddina Bele Whole White, 1 Kg', 200.00, 'images/FOOD/fooditems/tatauraddal1kg.webp', 5, 100, 'For most Indians, comfort food is always linked to easy-to-cook homemade meals and what can be the most convenient and quick to prepare dal. Urad Whole dal can be used to make idlis and dosas. Tata Sampann Urad Whole dal is unpolished as it does not undergo any artificial polishing with water, oil, or leather thereby retaining its goodness and wholesomeness. The 5-step process ensures that Tata Sampann Urad Whole dal grains are uniform and of premium quality, giving you an all-natural, authentic taste. So, whenever you are in the mood to cook something easy and delicious, dive into the scrumptious taste of Tata Sampann pulses, and enjoy a lovely meal! ||\r\n\r\nExplore Tata Sampann Pulses range - Toor dal, Chana dal, Moong dal, Moong dal Chilka, Green Moong, Masoor dal, Masoor Small dal, Masoor Whole dal, Kali Masoor dal, Urad dal, Urad Whole dal, Urad Kali, Chawli (Lobia), Kabuli Chana, Kala Chana, Matki (Moth bean) and Rajma. ||\r\n\r\nAlso Try: Try chana dal, toor dal, moong dal, masoor dal, Kabuli chana, etc.', '2021-05-22 14:51:36', 'food'),
(32, 'Staples', 'Safe Harvest Tur Dal - Pesticide Free, 1 kg', 179.00, 'images/FOOD/fooditems/safeharvestdal1kg.webp', 5, 100, 'Grown by marginal farmers in the rain-fed regions of Telangana, our Tur Dal is not only rich in proteins, calcium, iron and essential amino acids as it is unpolished to preserve all its nutritive goodness for your family and you. This single origin dal always ensures consistency in taste, texture and cooking time. All Safe Harvest products are cultivated completely devoid of synthetic chemical pesticides.', '2021-05-22 15:45:05', 'food'),
(33, 'Staples', 'India Gate Quinoa, 500 g', 250.00, 'images/FOOD/fooditems/quinao0.5kg.webp', 5, 100, 'Quinoa (pronounced as Keen-o-wah) is a super grain & one of the worlds most popular health foods. Quinoa being a highly nutritious product is packed with numerous health benefits. India Gate Being Worlds largest Rice millers & Basmati Rice exporter launched India Gate Quinoa after rigrous research to make this delicious & super healthy food part of every day plate for a healthier & happier India. ', '2021-05-22 15:45:05', 'food'),
(34, 'Staples', 'India Gate Basmati Rice/Basmati Akki - Feast Rozzana, 5 kg Pouch', 450.00, 'images/FOOD/fooditems/indiagaterice1kg.webp', 5, 100, 'India Gate Basmati Rice Feast Rozzana is defined by its long grains and amazing aromatic flavour. Having this rice is truly having a feast rozzana (a daily feast); combine it with your veggies and serve a nice pulao. Without this Basmati Rice, your biryanis will seem dull and tasteless. This is the perfect ingredient for different rice recipes. || \r\nThe long-grained cultured basmati which has been matured for one year comes to your home in the form of India Gate Basmati Rice Feast Rozzana. Grown in the most fertile region of the Indo-Gangetic Plains beneath the Himalayan sub-range, Basmati receives its nutty taste and characteristic aroma because of the fertile alluvial soil and the cold and fresh air of the region. Like wine, it gets better with age; maturing it for one to two years intensifies its taste and aroma.', '2021-05-22 15:58:13', 'food'),
(35, 'Staples', 'Daawat Basmati Rice/Basmati Akki - Sehat Mini Mogra, 10 kg\r\n', 525.00, 'images/FOOD/fooditems/dawatmograrice10kg.webp', 5, 100, '\r\nDaawat Mini Mogra is pure basmati which comes from our premium Specialist range for its smaller size. It has all the magnificent qualities of pure basmati uniformly graded by our aromatic sortex machines into different sizes & rozana brands, which you may buy as per your rice preparation. Once a luxury enjoyed only by royalty, the queen of rice can now grace your dining table every day. Rozana short length basmati promises the authentic taste and fragrance of basmati harvested from the finest seeds, at a price that fits into every budget! || \r\nEnergy 348 Kcal, Carbohydrate 78g, Sugars 0g, Protein 8.2g, Total Fat 0.5g, Saturated fat 0.1g, Trans Fat 0g, Cholesterol 0 mg, Sodium 0.75 mg, Dietary Fibre 1.9g, Calcium 7.6 mg, Iron 1.08mg', '2021-05-22 15:58:13', 'food'),
(36, 'Staples', 'Kohinoor Charminar Brown Rice/Akki, 1 kg', 109.00, 'images/FOOD/fooditems/charminarbrownrice1kg.webp', 5, 100, 'Kohinoor Charminar Brown Rice is deliciously nutritious and flavorful. A dish of steamy and fluffy brown rice, with a delectably mild & nutty flavor, is all you need to add a healthy touch to your everyday diet. Made of whole grain, it helps you lead an active life. No wonder, it is the healthy choice, for healthy families. ||\r\nBest value brown rice, \r\nFor daily health, \r\nHigh in fibre, \r\nLow GI value, \r\nGluten Free, \r\nIt’s easy to digest, \r\nHealthier than regular rice.', '2021-05-22 16:02:45', 'food'),
(37, 'Staples', 'India Gate Basmati Rice/Basmati Akki - Classic, 1 kg', 210.00, 'images/FOOD/fooditems/indiagatebasmaticlassicrice5kg.webp', 5, 100, 'India Gate Basmati Rice/Basmati Akki - Classic', '2021-05-22 16:02:45', 'food'),
(38, 'Staples', 'Kohinoor Basmati Rice/Basmati Akki - Royale, Authentic Biryani, 5 kg', 925.00, 'images/FOOD/fooditems/kohinoorbiryanirice5kg.webp', 5, 100, '\r\nThe extra-long and flavorful grains of Kohinoor Royale Authentic Basmati rice are best suited for special dishes like Biryani. They bring out the true flavors of every ingredient to give you the most authentic experience. Kohinoor Royale Basmati Rice is ideal for both everyday consumption and for special occasions when you want to put up your best dishes. It is characterized by long grains that double in size when cooked. ||\r\nNutritional Facts: \r\nFor every serving for 100 gm of uncooked rice, Energy (Kcal) 293, Protein (g) 6, Fat, Total (g) 0.5, Carbohydrate (g) 66, Dietary fiber (g) 3, Sugar (g) <0.1 .', '2021-05-22 16:07:01', 'food'),
(39, 'Staples', 'Safe Harvest Sona Masuri Raw Rice/Akki - 12 Months, 5 kg', 429.00, 'images/FOOD/fooditems/safeharvestrice.webp', 5, 100, 'Our Sona Masoori is grown in the soils of North Karnataka irrigated from the waters of the Krishna and Tungabhadra rivers. This paddy is aged for 12 months to allow the grain attain its best consistency when cooked while retaining a fluffy texture as is a great short grain variety for pressure cooking and boiling for both Indian and Oriental dishes. All Safe Harvest products are cultivated completely devoid of synthetic chemical pesticides.', '2021-05-22 16:07:01', 'food'),
(40, 'Staples', 'Daawat Basmati Rice/Basmati Akki - Rozana Gold, 5kg ', 445.00, 'images/FOOD/fooditems/dawatricegold5kg.webp', 5, 100, 'Daawat Rozana Gold is the finest Basmati Rice in the mid-price affordable segment. Rozana Gold has 3/4th length of the basmati grains It is specially processed for daily cooking across a multitude of regular dishes, a perfect fit for every day consumption. It promises a sweet taste and rich aroma as each grain is naturally aged.\r\nClick here for unique and delicious recipes - https://www.bigbasket.com/flavors/collections/233/rice-rice-products ||\r\nNutritional Facts: \r\nEnergy 348 Kcal, Carbohydate 78g, Sugars 0g, Protein 8.2g, Total Fat 0.5g, Saturated fat 0.1g, Trans Fat 0g, Cholesterol 0 mg, Sodium 0.75 mg, Dietary Fibre 1.9g, Calcium 7.6 mg, Iron 1.08mg', '2021-05-22 16:12:06', 'food'),
(41, 'Staples', 'India Gate Basmati Rice/Basmati Akki - Dubar, 1kg', 118.00, 'images/FOOD/fooditems/indiagatericedabur1kg.webp', 5, 100, 'India Gate Basmati Rice/Basmati Akki - Dubar', '2021-05-22 16:12:06', 'food'),
(42, 'Staples', 'Daawat Basmati Rice/Basmati Akki - Super, 5 kg Pouch', 845.00, 'images/FOOD/fooditems/kohinoorfluffyrice5kg.webp', 5, 100, 'Versatile, fine, long-grained and perfectly textured. ‚ Basmati rice fit for a King. Daawat Super is aged to perfection. || \r\nNutritional Facts:\r\nEnergy 350Kcal, Carbohydate 78g, Sugars 0g, Protein 8.8g, Total Fat 0.47g, Saturated fat 0.1g, Trans Fat 0g, Cholesterol 0 mg, Sodium 1.7 mg, Dietary Fibre 1.6g, Calcium 5.9mg, Iron 1.08mg', '2021-05-22 16:35:57', 'food'),
(43, 'Staples', 'India Gate Basmati Rice/Basmati Akki - Feast Rozzana, 5 kg Pouch', 450.00, 'images/FOOD/fooditems/indiagaterice1kg.webp', 5, 100, 'India Gate Basmati Rice Feast Rozzana is defined by its long grains and amazing aromatic flavour. Having this rice is truly having a feast rozzana (a daily feast); combine it with your veggies and serve a nice pulao. Without this Basmati Rice, your biryanis will seem dull and tasteless. This is the perfect ingredient for different rice recipes. || \r\nBasmati rice has complex carbohydrates which mean that it can be digested easily and can be considered as an instant energy source. Rice has little protein, but the protein is rich in eight amino acids; plus as this is a gluten-free grain, people who are gluten-intolerant can consume this rice without problem.', '2021-05-22 16:35:57', 'food'),
(44, 'Oils', 'Fortune Kachi Ghani Mustard Oil, 500 ml Bottle', 117.00, 'images/Food/fooditems/fortunekachighani500ml.webp', 5, 100, 'Fortune Kachi Ghani Mustard Oil, traditionally extracted from the first press of mustard seeds, comes with a high pungency level and strong aroma. Being pure, our cooking oil retains its natural properties and mustard oil benefits. Its strong aroma and pungency spice up your cooking. ||\r\n\r\nNutritional Facts:\r\nFat - 100g, Mono Unsaturated Faty Acids - 66g, Energy - 900 cals.', '2021-05-22 16:48:33', 'food'),
(45, 'Oils', 'Fortune Sun Lite - Sunflower Refined Oil, 1 L Pouch', 233.00, 'images/Food/fooditems/fortunesunlite1l.webp', 5, 100, 'Fortune Sunflower Oil is a light, healthy and nutritious cooking oil. Being rich in vitamins and consisting mainly of polyunsaturated fatty acids, it makes food easy to digest. ||\r\nNutritional Facts:\r\nEnergy - 900 Kcal; Carbohydrates, Protein - 0g; Cholestrol - 0g; Fat - 100g; Saturated Fatty Acid - 12g; Mono Unsaturated Fatty Acid  - 26g; Poly Unsaturated Fatty Acid  - 2g; ', '2021-05-22 16:48:33', 'food'),
(46, 'Oils', 'Fortune Rice Bran Health Oil - Cooking Oil For Healthier Heart, 1 L', 215.00, 'images/FOOD/fooditems/fortunericebran1l.webp', 5, 100, 'Fortune Rice Bran Health Oil is 100% Physically Refined Rice Bran Oil which is Rich in Gamma Oryzanol. It helps in reducing Bad Cholesterol & increases Good Cholesterol which is beneficial for your heart health. Along with Vitamin A/D/E, it is rich in Natural Antioxidants which boosts immunity and gives many other health benefits to every member of the family. It is best suited for Indian cooking as it has a high smoke point which is ideal for deep frying/ stir-frying. Fortune Rice bran health oil naturally has the most ideal SFA-MUFA-PUFA ratio required by our body, this is one reason for which Doctors & Nutritionists prescribe changing oils frequently. Rice Bran Oil is considered a wonder oil in many countries. World Health Organisation (WHO) & American Heart Association (AHA) recommend Rice Bran Oil as one of the Healthiest oils for the heart. ||\r\n\r\nFeatures: \r\n- Cholesterol-lowering, heart-healthy cooking oil\r\n\r\n- Improves HDL and LDL ratio, healthier heart\r\n\r\n- Balanced pufa and mufa ratio, cleaner blood vessels\r\n\r\n- Rich in Natural Antioxidants: Boosts immunity ', '2021-05-22 16:52:15', 'food'),
(47, 'Oils', 'Saffola Gold Pro Healthy Lifestyle Edible Oil, 5 L Jar', 1138.00, 'images/FOOD/fooditems/saffolagold5l.webp', 5, 100, 'Today our food habits, stress & low activity level affect our health. And without realising it, our heart health too. A healthy heart is among the first steps to overall health. So it is not about taking care when a problem arises, but ensuring you take small steps today to take pro-active care of your heart and health. The easiest step is to switch to heart healthy foods. And choosing the right cooking oil can help make your meals better for your heart health. New Saffola Gold blended edible oil can help keep your family heart healthy. It helps keep your cholesterol in check^. This vegetable oil\'s dual seed technology gives you the goodness of 2 oils in 1, rice bran oil & sunflower oil that ensures a good balance of MUFA & PUFA for better nutrition from fats, compared to single seed oils. It also has benefit of anti-oxidants that help fight free radicals. New Saffola Gold has Oryzanol that helps maintain healthy cholesterol levels. New Saffola Gold cooking oil comes with LOSORB™ technology which ensures that your food absorbs upto 33%* lesser oil . So choose Saffola Gold, a smart way to keep your heart healthy! ^Helps manage cholesterol better than commonly consumed oils, based on, randomized, double blind clinical study 2019, as approved by independent ethics committee. Saffola encourages you to use less oil, exercise regularly and have a balanced lifestyle. *as compared to commonly consumed cooking oils; basis frying studies on potato, 2019.', '2021-05-22 16:52:15', 'food'),
(48, 'Oils', 'Saffola Tasty Pro Fitness Conscious Edible Oil, 1 L Pouch', 178.00, 'images/Food/fooditems/saffolatasty1l.webp', 5, 100, '\r\nWe understand the staying fit is important for you and your family. So when it comes to food, it important that you make the right choices to ensure your efforts are fruitful. Oil is an essential ingredient in your meals. Most often, the first step will be to reduce the amount of oil used. But that might not be enough. You need to choose the right cooking oil that works as hard as you do. With LOSORB™ technology, Saffola Tasty blended edible oil ensures that your food absorbs upto 29% lesser oil*. Its dual speed technology helps with a good balance of MUFA & PUFA, providing you with complete nutrition from fats. This vegetable oil brings alive the natural flavour of the food cooked & spices used, without altering any flavour. Since the quantity of oil consumed every day is as important as the quality of oil you choose for daily cooking, Saffola Tasty cooking oil helps you ensure both. Complement your fitness efforts with healthy choices. Choose Saffola Tasty!  ||\r\nFeatures\r\nWith LOSORB™ Technology that ensures your food absorbs upto 29% less oil, \r\nSaffola Tasty’s Dual Seed Technology gives you the goodness of 2 oils in 1, \r\nIt ensures a good balance of MUFA and PUFA for better nutrition through fats, compared to single seed oils, With Oryzanol helps maintain healthy cholesterol levels\r\nFortified with Vitamin A which helps against night blindness & Vitamin D which supports strong bones\r\n', '2021-05-22 16:56:48', 'food'),
(49, 'Oils', 'Amul Pure Ghee/Tuppa, 1 L Tin', 550.00, 'images/Food/fooditems/amulpureghee1l.webp', 5, 100, 'Clarified Butter or Pure Ghee is a staple in Indian Kitchens. Known to be rich in antioxidants and trans fat, this product from the house of Amul can be used for cooking and aids people in the weight management process as well. Amul is well known for its wide range of high-quality dairy products. ||\r\n\r\nNutritional Facts:\r\nPer 100 ml Energy: 814 kcal Energy from Fat: 814 kcal Total Fat: 90.5 g Saturated fat: 58 g Cholesterol: 190 mg Sodium: 0 mg Total Carbohydrate: 0 g Sugar: 0 g Protein: 0 g Vitamin A: 78 mcg', '2021-05-22 16:56:48', 'food'),
(50, 'Oils', 'BORGES Olive Oil - Extra Light, 2 L Bottle', 2600.00, 'images/Food/fooditems/borgesoliveoil2l.webp', 5, 100, 'Borges Extra Light Olive oil is handcrafted in Spain keeping in mind the Indian cooking methods. The olive oil is light in flavour & mild in the aroma which does not interfere with the original flavor of the dishes. Extra Light Olive oil has a high smoking point which makes it perfect for any kind of high heat cooking including frying. And being an olive oil of the highest quality, it has all the health benefits like 75% MUFA, natural anti-oxidants, phenols and Vitamins that helps in all-round health of your body. ', '2021-05-22 17:00:31', 'food'),
(51, 'Oils', 'Fortune Sun Lite - Sunflower Refined Oil, 5 L Can', 1195.00, 'images/Food/fooditems/fortunesunlite5l.webp', 5, 100, 'Fortune Sunflower Oil is a light, healthy and nutritious cooking oil. Being rich in vitamins and consisting mainly of polyunsaturated fatty acids, it makes food easy to digest. ||\r\n\r\nNutritional Facts:\r\nEnergy - 900 Kcal; Carbohydrates, Protein - 0g; Cholestrol - 0g; Fat - 100g; Saturated Fatty Acid - 12g; Mono Unsaturated Fatty Acid - 26g; Poly Unsaturated Fatty Acid - 2g; Added Vitamin A 750 mcg; Added Vitamin A 11.25 mcg; **mcg stands for microgram; @ at the time of packing.', '2021-05-22 17:00:31', 'food'),
(52, 'Oils', 'Saffola Active Pro Weight Watchers Edible Oil, 1 L Pouch', 213.00, 'images/FOOD/fooditems/saffolaactive1l.webp', 5, 100, 'You work hard to stay fit and watch your weight. So when it comes to food, it is important that you make the right choices to ensure your efforts are fruitful. Oil is an essential ingredient in your meals. Most often, the first step will be to reduce the amount of oil used. But that might not be enough. You need to choose the right cooking oil that works as hard as you do. Saffola Active blended edible oil comes with LOSORB™ technology which results in upto 27% lesser oil* so that you consume less oil every meal. Saffola Active cooking oil is high in Omega-3 (alpha linolenic acid), which contributes to the maintenance of normal blood cholesterol levels. Saffola Active’s Dual Seed Technology gives you the goodness of 2 oils in 1. It ensures a good balance of MUFA and PUFA for better nutrition through fats, compared to single seed oils. Since quantity of oil consumed every day is as important as the quality of oil you choose for daily cooking, Saffola Active blended edible vegetable oil helps you ensure both. Boost your efforts to stay active by choosing Saffola Active! *as compared to commonly consumed cooking oils; basis frying studies on potato, 2018.', '2021-05-22 17:03:48', 'food'),
(53, 'Oils', 'Gemini Sunflower Oil - With Nutri Fresh Technology, 1 L Pouch\r\n', 195.00, 'images/FOOD/fooditems/geminisunfloweroil1l.webp', 5, 100, 'Gemini Sunflower Oil comes with NutriFreshLock Technology that helps to retain the nutrients and freshness of your food for long time; unlocking time for you to chase your dreams. || \r\n\r\nIngredients: \r\nSun Flower Seeds, Vitamin E (273 mg), Vitamin D (5 mg), Vitamin A (750 mcg) and Dimethyl Polysiloxane', '2021-05-22 17:03:48', 'food'),
(54, 'Oils', 'mother dairy Pure Cow - Ghee/Tuppa, 1 L Pouch', 500.00, 'images/FOOD/fooditems/motherdairyghee1l.webp', 5, 100, 'In Ayurveda, Cow ghee is believed to be the best for human consumption. It is considered as rasayana, a rejuvenating and longevity promoting food. It is a rich source of Vitamin A which is essential for vision, body growth, bone metabolism and immune function. ||\r\nNutrional Facts:\r\nEnergy - 896 kcal, Protein - 0.0 g, Carbohydrate - 0 g, Fat - 0 g', '2021-05-22 17:06:43', 'food'),
(55, 'Oils', 'mother dairy Pure Cow - Ghee/Tuppa, 500 ml Pouch', 280.00, 'images/FOOD/fooditems/motherdairyghee1l.webp', 5, 100, 'In Ayurveda, Cow ghee is believed to be the best for human consumption. It is considered as rasayana, a rejuvenating and longevity promoting food. It is a rich source of Vitamin A which is essential for vision, body growth, bone metabolism and immune function. ||\r\nNutrional Facts:\r\nEnergy - 896 kcal, Protein - 0.0 g, Carbohydrate - 0 g, Fat - 0 g', '2021-05-22 17:06:43', 'food'),
(56, 'Oils', 'Sundrop Superlite Advanced Oil - Sunflower, 3 L Can', 729.00, 'images/FOOD/fooditems/sundropsunlite5l.webp', 5, 100, 'Sundrop Superlite Advanced Oil ensures that the absorption of oil while cooking is less than compared to any ordinary oil. Its advanced refining process makes it extra light, which is enriched with Vitamin A and D that takes care of upto 25% of the daily requirement of essential vitamins. So when you cook food using Sundrop SuperLite Advanced Oil your family eats well and stays active throughout the day. Enjoy this premium oil by Sundrop at super savings with this 3 Litre Jar. Brought to you by Sundrop - Healthy Oil for Healthy People.', '2021-05-22 17:09:39', 'food'),
(57, 'Oils', 'Maxcare Virgin Coconut Oil (Cold Pressed), 1 L', 770.00, 'images/FOOD/fooditems/coconutoil1l.webp', 5, 100, '\r\nMax Care Virgin Coconut Oil (VCO) is pure, unrefined, cold pressed oil extracted from fresh coconut milk. The cold process method ensures that all the vital nutrients and the natural goodness of fresh coconuts are retained. A lot of the coconut oils in the market are made from copra or dehydrated coconut meat using heat. However, Max Care VCO is extracted from fresh coconuts without the use of any heat, making it the finest quality of coconut oil with a delicate, mild aroma & taste, and water like clarity. Max Care VCO is a superfood, rich in several essential fatty acids and antioxidants, making it one of the healthiest oils for cooking, frying and baking. Apart from cooking, it can also be consumed in its raw form or added to salads, smoothies or food. VCO is rich in lauric acid, which is found naturally only in mother’s milk apart from Virgin Coconut Oil. This lauric acid helps improve immunity and boosts metabolism. Additionally, Max Care VCO can also be used externally on hair & skin and is an excellent natural moisturizer and conditioner that nourishes the skin and hair. Being 100% natural and nutritious, the oil is an excellent massage oil for babies as well.', '2021-05-22 17:09:39', 'food'),
(58, 'Oils', 'Saffola Extra Virgin Olive Oil, 1 L', 1050.00, 'images/FOOD/fooditems/saffolaolive1l.webp', 5, 100, 'When it comes to nutrition-dense superfoods, extra virgin Olive Oil is a wonderful culinary addition to your kitchen. Saffola Aura Extra Virgin Olive Oil is a premium edible oil, imported from Spain, rich in monounsaturated fatty acids and natural antioxidants. It is extracted from carefully plucked olives from Spanish orchards and then imported to India. Extra virgin olive oil is cold-pressed to retain its naturally occurring flavours and properties.\r\n\r\nThis process ensures natural olive extract infused in every drop of our final product. It has a rich and flavourful taste that beautifully complements your cooking, making it perfect for modern lifestyles. It is widely used in salad dressings, dips, spreads, garnishing’s, drizzling and flavouring. Also try, our Saffola Aura Refined Olive Oil variant that you can use for everyday cooking like stir-frying, sautéing, roasting, grilling, baking etc.', '2021-05-22 17:13:26', 'food'),
(59, 'Oils', 'Del Monte Extra Virgin Olive Oil, 500 ml Plastic Bottle', 850.00, 'images/FOOD/fooditems/delmonte500mlolive.webp', 5, 100, 'Del Monte Extra Virgin Olive Oil is obtained by strict processing of olives (with the temperature being maintained below 27 deg C while making an olive paste)** through a cold extraction process which ensures it\'s a great flavour and nice aroma, with all it\'s health benefits intact.\r\nDel Monte Extra Virgin Olive Oil is the highest grade of olive oil with an excellent aroma and flavour.\r\nDerived from the cold extraction of the olive fruit within 24 hours of harvesting, it lends an amazing flavour to your salads & other recipes.\r\nRich in MUFA / PUFA ( Good Fats )', '2021-05-22 17:13:26', 'food'),
(60, 'Spices', 'Mother\'s Recipe Paste - Ginger & Garlic, 200 g Pouch', 50.00, 'images/FOOD/fooditems/motherchoicegingerpaste.webp', 5, 100, 'Mothers Recipe contains one of the most necessary ingredients in Indian cuisines. It guarantees that the paste comes to you in its tastiest form. Enjoy having the taste of mothers made Ginger & Garlic Paste.', '2021-05-22 20:32:24', 'food'),
(61, 'Spices', 'Tata Sampann Turmeric Powder/Arisina Pudi, 200 g', 62.00, 'images/FOOD/fooditems/tatasampannhaldi.webp', 5, 100, 'Tata Sampann’s range of spices are crafted to satisfy your taste buds. Tata Sampann sources all its spices & masalas from the most authentic places i.e. chillies from Guntur, Andhra Pradesh, coriander powder from Kumbhraj, Madhya Pradesh, kasuri methi from Nagaur and turmeric from Salem, Tamil Nadu. Tata Sampann Turmeric Powder is sourced from Salem region in Tamil Nadu, which is famous for its rich yellow highly aromatic turmeric. Made from whole spices that contain natural oils, haldi has an active ingredient called curcumin which is known to act as an antioxidant*. This turmeric powder can be teamed up with pulao, greenies, vegetable soup or smoothies, the choice is yours!\r\nStorage Instructions: Store in a cool and dry place. *Based on internal samples tested for naturally present volatile oil and curcumin content.\r\nHighly Aromatic Turmeric: Enjoy the rich taste of Tata Sampann Turmeric Powder in all your favourite dishes\r\n3% Curcumin: Every pack carries the promise of an active ingredient called curcumin which is known to act as an antioxidant\r\nSourced from Salem: The turmeric is of the Salem variety, which is named after a region in Tamil Nadu\r\nContain Natural Oils*: Made from whole spices which contain natural oils\r\nAlso Try: Try Tata Sampann Red Chilli Powder, Tata Sampann Coriander Powder and Tata Sampann Kasuri Methi\r\n', '2021-05-22 20:32:24', 'food'),
(62, 'Spices', 'Everest Garam Masala, 100 g Carton', 80.00, 'images/FOOD/fooditems/everestgarammasala100g.webp', 5, 100, 'Everest Garam Masala has been an evergreen taste enhancer for several years in India. It is a combine of 13 spices, with chilli powder as the support zest. The masala known for adding the savor to dishes also gives thick red colour to the ever unusual Indian dishes. ||\r\nIngredients:\r\nCoriander, Black pepper, Cumin seed, Dry ginger, Cinnamon, Aniseed, Cardamom, Cloves, Nutmeg, Salt.', '2021-05-22 20:36:02', 'food'),
(63, 'Spices', 'Everest Tikhalal Chilli Powder/Menasina Pudi, 500 g Pouch', 225.00, 'images/FOOD/fooditems/everestredchiili500g.webp', 5, 100, 'Everest Tikhalal Powder contains roasted, dried and powdered red chillies that can add a punch to any dish. This pack is vacuum sealed and its inmates are prepped under the highest quality procedures. The selection of chillies also takes place under a highly qualitative eye. It also contains 2% edible groundnut oil.', '2021-05-22 20:36:02', 'food'),
(64, 'Spices', 'Everest Turmeric Powder/Arisina Pudi, 200 g Pouch', 62.00, 'images/FOOD/fooditems/everesthaldi200g.webp', 5, 100, 'Turmeric Powder is one along with those spices to be proved as a best result of Everest. The part of Turmeric powder is very much necessary to make our eating stuffs or dishes scented and colored. Turmeric has a soft, earthy and woody aroma. It stimulates protein digestion, and is a superb blood purifier. It is a accepted variety in India, where turmeric is used as a solution coloring agent in \'curries\'.', '2021-05-22 20:39:21', 'food'),
(65, 'Spices', 'MAGGI Masala-Ae-Magic Seasoning - Vegetable Masala, 6 g (Pack of 12)', 58.00, 'images/FOOD/fooditems/maggimasala6g.webp', 5, 100, 'Ingredients: \r\nMixed spices (38.7%) [Roasted spice powder (14%) (Coriander, Turmeric (3.5%), Cumin (1.7%), Aniseed (1.4%), Black pepper (0.9%), Fenugreek (0.7%), Ginger, Clove (0.3%), Green cardamom (0.3%), Nutmeg (0.3%)), Red chilli powder (7%), Dehydrated onion, Dried garlic, Capsicum extract, Roasted cumin powder (3.5%),Spice extract blend (Capsicum extract, Coriander extract, Cumin extract ( 0.001%))] , Iodised salt, Sugar, Flavour enhancer (635), Palm oil, Edible starch, Vitamin mineral premix [Minerals (Ferric pyrophosphate, Potassium iodate), Carrier (Starch), Vitamin (Retinyl acetate)], Acidity regulator (330) and Caramel salt mix (Iodised salt, Colour (150d), Palm oil).', '2021-05-22 20:39:21', 'food'),
(66, 'Spices', 'Tata Sampann Chilli Powder/Menasina Pudi, 100 g', 70.00, 'images/FOOD/fooditems/tatasampannchilli100g.webp', 5, 100, 'Grasp the fresh, fine grade tata chili powder to increase up the pungency of your culinary preparations that you frequently consume. Let the flavor go high with the culinary preparations you create with it. Chili powder is also utilized as a colour and flavor enhancer in the indian cuisines.', '2021-05-23 20:40:38', 'food'),
(67, 'Spices', 'Everest Powder - Black Pepper, 50 g Carton', 75.00, 'images/FOOD/fooditems/everestblackpepper50g.webp', 5, 100, 'Everest presents their authentic range of masalas that are blended with a wide variety of handpicked and selected spices that bring a whole new flavour and meaning to your dishes. Rake up your favourite recipes and cuisines by adding this magical blend of Everest masalas.', '2021-05-23 20:40:38', 'food'),
(68, 'Spices', 'Everest Chicken Masala, 50 g Carton', 40.00, 'images/FOOD/fooditems/everestchickenmasala50g.webp', 5, 100, 'Asafoetida, Bengal Gram, Black Cardamom, Black Gram, Black Pepper, Cardamom Seeds, Cassia, Chilli, Clove, Common Salt, Coriander Cumin, Dry Ginger, Garlic, Fenugreek, Kasuri Methi, Mace, Nutmeg, Poppy Seeds, Turmeric.', '2021-05-23 20:43:57', 'food'),
(69, 'Spices', 'Kohinoor Ready Masala - Hyderabadi Biryani, 15 g', 20.00, 'images/FOOD/fooditems/kohinoorbiryanimasala15g.webp', 5, 100, 'A biryani that comes straight from the kitchens of the Nizams. Its rich flavours and enticing aroma make it a legendary dish that can turn an ordinary meal into a feast. This masala is crafted by the culinary experts.', '2021-05-23 20:43:57', 'food'),
(70, 'Spices', 'Mdh Masala - Pav Bhaji, 50 g Carton', 36.00, 'images/FOOD/fooditems/mdhpavmasala50g.webp', 5, 100, 'lorem40', '2021-05-23 20:49:02', 'food'),
(71, 'Spices', 'Everest Pani Puri Masala, 50 g Carton', 35.00, 'images/FOOD/fooditems/everestpanipuri50g.webp', 5, 100, 'Pani in Hindi means water. Puri is a fried hollow ball made from wheat flour. The Puri is punctured open on one side and stuffed with delicious fillings and topped with Pani. The Puri is then eaten in a mouth full. This is one of Indias most popular outdoor snacks.\r\nBlack Pepper, Tamarind, and Dry Ginger combine together to give a sharp twinkle to this Everest Blend that spices the Pani.', '2021-05-23 20:49:02', 'food'),
(72, 'Philosophy', 'Death; An Inside Story  (English, Paperback, Sadhguru)', 299.00, 'images/stationary/books/religion1.jpeg', 6, 100, 'Death is a taboo in most societies in the world. But what if we have got this completely wrong? What if death was not the catastrophe it is made out to be but an essential aspect of life, rife with spiritual possibilities for transcendence? For the first time, someone is saying just that. In this unique treatise-like exposition, Sadhguru dwells extensively upon his inner experience as he expounds on the more profound aspects of death that are rarely spoken about. From a practical standpoint, he elaborates on what preparations one can make for one\'s death, how best we can assist someone who is dying and how we can continue to support their journey even after death. Whether a believer or not, a devotee or an agnostic, an accomplished seeker or a simpleton, this is truly a book for all those who shall die!\r\n', '2021-05-23 21:22:15', 'book'),
(73, 'Philosophy', 'Life\'s Amazing Secrets  (English, Paperback, Das Gaur Gopal)', 250.00, 'images/stationary/books/religion15.jpeg', 6, 100, '\r\nSummary of the Book: \r\nLife\'s Amazing Secrets: How to Find Balance and Purpose in Your Life is an engaging philosophical book that deals with deep and meaningful conversations on life between Gaur Gopal Das himself and his wealthy friend Harry. The conversation ranges from human conditions to finding one’s purpose in life. Whether you are on a journey to discover your true potential in life, looking for ways to strengthen your relationships or keys to stay happy in life, the author takes you through a beautiful journey with his insightful thoughts on these areas of life. Read this book to undertake this journey and discover the real you in the process.\r\n|| \r\nAbout the Author: \r\n\r\nGaur Gopal Das is a monk whose ideologies and perspectives on ancient philosophy and modernity has made him a life coach to thousands of people around the globe. Das has been travelling the world since 2015 to share his wisdom with several people and corporate companies. He even posts various motivational videos and posts on social media, thereby making him one of the most famous monks in the world. His book, Life’s Amazing Secrets, talks about the different ways by which one can find a balance and purpose in life.', '2021-05-23 21:22:15', 'book'),
(74, 'Philosophy', 'Inner Engineering - A Yogi\'s Guide to Joy(English, Paperback, unknown)', 299.00, 'images/stationary/books/religion2.jpeg', 6, 100, '\r\nSummary of the Book:\r\nSadhguru’s Inner Engineering:A Yogi\'s Guide to Joy presents the western readers with a path to achieve a complete sense of well-being through yoga for the very first time. In this philosophical book, Sadhguru narrates his own story of His awakening, right from childhood to his time as an avid bike rider when he had crossed the Indian subcontinent on his motorcycle. Read this book and get inspired by Sadhguru’s life and teachings.\r\n|| \r\nAbout the Author:\r\n\r\nSadhguru Jaggi Vasudev, also reverently known as Sadhguru is an Indian Yogi, mystic and an author as well. He is also globally known as the founder of Isha Foundation, a not-for-profit organisation that offers yoga programmes in different parts of the world. Sadhguru’s books have also appeared in the New York Times Bestseller List in various categories such as ‘Health’, ‘Religion’, ‘Spirituality and Faith’, etc. Some of his other books include Life and Death in one breath, Encounter the Enlightened, Essential Wisdom From a Spiritual Master and many more.', '2021-05-23 21:28:45', 'book'),
(75, 'Philosophy', 'Adiyogi: The Source of Yoga  (English, Paperback, Sadhguru)', 299.00, 'images/stationary/books/religion3.jpeg', 6, 100, '\r\n\"Shiva does not spell religion. Shiva spells responsibility -- our ability to take our very life process in our hands.\'\' -- Sadhguru \'Shi-va\' is \'that which is not\', a primordial emptiness; Shiva is also the first-ever yogi, Adiyogi, the one who first perceived this emptiness. Adiyogi is symbol and myth, historic figure and living presence, creator and destroyer, outlaw and ascetic, cosmic dancer and passionate lover, all at once. A book like no other, this extraordinary document is a tribute to Shiva, the Adiyogi, by a living yogi; a chronicle of the progenitor of mysticism by a contemporary mystic. Here science and philosophy merge seamlessly, so do silence and sound, question and answer--to capture the unspeakable enigma of Adiyogi in a spellbinding wave of words and ideas that will leave one entranced, transformed.', '2021-05-23 21:28:45', 'book'),
(76, 'Philosophy', 'Mahayoddha Kalki: Sword of Shiva(English, Missal Kevin)', 250.00, 'images/stationary/books/religion5.jpeg', 6, 100, 'Book Details ||\r\nImprint: \r\nFingerprint Publishing || \r\nPublication Year:\r\nSeptember', '2021-05-23 21:35:50', 'book'),
(77, 'Philosophy', 'Chanakya Neeti  (Hindi, Paperback, Parashar Ashwini)', 150.00, 'images/stationary/books/religion16.jpeg', 6, 100, 'Imprint:\r\nDiamond Pocket Books', '2021-05-23 21:35:50', 'book'),
(78, 'Philosophy', 'Sita  (English, Paperback, Pattanaik Devdutt)', 499.00, 'images/stationary/books/religion14.jpeg', 7, 100, '\r\nSita: An Illustrated Retelling Of The Ramayana is the Ramayana retold with the focus of the story being on Sita, Rama’s devoted and loyal wife.\r\nEven though Sita plays a pivotal role in the Ramayana, when you actually seek her out you realize she is but a prop, appearing and disappearing, with her marriage, her abduction, her rescue and finally her banishment. Who is she really? There are tantalizing clues in classical as well as subaltern literature and in folk traditions, but nothing else.', '2021-05-24 03:44:32', 'book'),
(79, 'Philosophy', 'The God Delusion  (English, Paperback, Dawkins Richard)', 599.00, 'images/stationary/books/religion11.jpeg', 6, 100, 'The God Delusion caused a sensation when it was published in 2006. Within weeks it became the most hotly debated topic, with Dawkins himself branded as either saint or sinner for presenting his hard-hitting, impassioned rebuttal of religion of all types. His argument could hardly be more topical. While Europe is becoming increasingly secularized, the rise of religious fundamentalism, whether in the Middle East or Middle America, is dramatically and dangerously dividing opinion around the world. In America, and elsewhere, a vigorous dispute between \'intelligent design\' and Darwinism is seriously undermining and restricting the teaching of science. In many countries religious dogma from medieval times still serves to abuse basic human rights such as women\'s and gay rights. And all from a belief in a God whose existence lacks evidence of any kind. Dawkins attacks God in all his forms. He eviscerates the major arguments for religion and demonstrates the supreme improbability of a supreme being. He shows how religion fuels war, foments bigotry and abuses children. The God Delusion is a brilliantly argued, fascinating polemic that will be required reading for anyone interested in this most emotional and important subject.', '2021-05-24 03:44:32', 'book'),
(80, 'Philosophy', 'Mythology  (English, Hardcover, Hamilton Edith)', 2404.00, 'images/stationary/books/religion20.jpeg', 6, 100, '\r\nSince its original publication by Little, Brown and Company in 1942, Edith Hamilton\'s Mythology has sold millions of copies throughout the word and established itself as a perennial bestseller in its various available formats: hardcover, trade paperback, mass market paperback, and e-book. For 75 years readers have chosen this book above all others to discover the thrilling, enchanting, and fascinating world of Western mythology-from Odysseus\'s adventure-filled journey to the Norse god Odin\'s effort to postpone the final day of doom. This exciting new deluxe, large-format hardcover edition, published in celebration of the book\'s 75th anniversary, will be beautifully packages and fully-illustrated throughout with all-new, specially commissioned four-color art, making it a true collector\'s item.', '2021-05-24 22:29:53', 'book'),
(81, 'Philosophy', 'Sri Ramakrishna - The Face of Silence  (English, Paperback, Nikhilananda Swami)', 399.00, 'images/stationary/books/religion23.jpeg', 6, 100, '', '2021-05-24 22:29:53', 'book'),
(82, 'Philosophy', 'Srimad Bhagvatgita(Hardcover, Hindi)', 500.00, 'images/stationary/books/religion4.jpeg', 6, 100, '', '2021-05-24 22:35:05', 'book'),
(83, 'Philosophy', 'Shri Tulsidas Krit Ramcharit Manas Ramayan By Manoj Publications(Hard, Hindi, Tulsi Das Ji)', 667.00, 'images/stationary/books/religion7.jpeg', 6, 100, '', '2021-05-24 22:35:05', 'book'),
(84, 'Philosophy', 'Happiness Unlimited-Awakening With Brahma Kumaris(English, Suresh Oberoi)', 250.00, 'images/stationary/books/religion9.jpeg', 6, 100, '\r\nIn these enlightening and eye-opening conversations, the renowned spiritual mentor, Sister BK Shivani reveals how to create a life of joy, contentment and bliss, because we all have the choice and the power to do so. According to her, the reason why there is so little happiness in the world is dependency. Happiness is not dependent on \'anything\' or \'anyone\', or found \'anywhere\'. We keep delaying our happiness until things are just right in our life. We think we will be happy in the future and then wonder why we are not happy now.Happiness is only possible when we are able to accept everyone as they are, at every moment, in every situation. This book is a medium for the awakening and acceptance of self-responsibility. Helping us choose our thoughts and feelings aligned with our true nature of purity, peace and love. To make us shift from asking to sharing; from holding on to letting go; from expectations to acceptance; from the past and the future to being in the now. Happiness is a \'decision\', not a \'consequence\'.About the Author Sister Shivani is a practitioner of Rajyoga Meditation of the Brahma Kumaris. With a background in engineering, her ability to analyze deep-rooted emotions like ego, stress, anger, fear etc, is empowering hundreds of thousands of people to take personal responsibility of their thoughts and choose a life where acceptance and contentment is natural. She presents a logical yet comfortable way of adopting spirituality. Suresh Oberoi is an internationally recognized Indian film actor having done over 250 films in the last 35 years. A multi-talented personality, he has excelled in all genres of the media. He has a keen interest in exploring and experiencing spirituality in practical life.', '2021-05-24 22:48:48', 'book');
INSERT INTO `mobile` (`item_id`, `item_brand`, `item_name`, `item_price`, `item_image`, `section_id`, `item_qty`, `item_descr`, `item_datetime`, `item_type`) VALUES
(85, 'Philosophy', 'My Hanuman Chalisa  (English, Paperback, Pattanaik Devdutt)', 295.00, 'images/stationary/books/religion10.jpeg', 6, 100, '\r\nDevdutt Pattanaik writes and lectures on the relevance of mythology in modern times. He has written over 500 articles in newspapers, and thirty books, which include My Gita, Business Sutra: A Very Indian Approach to Management, Jaya: An Illustrated Retelling of the Mahabharata, Sita: An Illustrated Retelling of the Ramayana, 7 Secrets of Hindu Calendar Art, 7 Secrets of Shiva, 7 Secrets of Vishnu, 7 Secrets of the Goddess, The Book of Ram, 99 Thoughts on Ganesha, Shikhandi and Other Tales They Don’t Tell You and Myth=Mithya: Decoding Hindu Mythology. He lives in Mumbai. For more information on Devdutt and his books, visit devdutt.com', '2021-05-24 22:48:48', 'book'),
(86, 'Philosophy', 'Muhammad  (English, Paperback, Lings Martin)', 450.00, 'images/stationary/books/religion17.jpeg', 6, 100, '', '2021-05-24 22:56:20', 'book'),
(87, 'Philosophy', 'Azadi  (English, Hardcover, Roy Arundhati)', 499.00, 'images/stationary/books/religion13.jpeg', 6, 100, 'Arundhati Roy is the author of The God of Small Things, which won the Booker Prize in 1997, and The Ministry of Utmost Happiness, which was longlisted for the Man Booker Prize in 2017. Both novels have been translated into more than forty languages. My Seditious Heart, published in 2019, collects the work of a two-decade period during which Roy devoted herself to the political essay as a way of opening up space for justice, rights, and freedoms in an increasingly hostile environment.\r\nDimensions\r\nHeight\r\n204 mm\r\nLength\r\n132 mm', '2021-05-24 22:56:20', 'book'),
(88, 'Biography', 'Why I am an Atheist and Other Works  (English, Paperback, Singh Bhagat)', 175.00, 'images/stationary/books/bio1.jpeg\r\n', 6, 100, '\r\nSrishti Publishers & Distributors', '2021-05-24 23:24:14', 'book'),
(89, 'Biography', 'The Story of My Experiments with Truth  (English, Paperback, Gandhi M. K.)', 175.00, 'images/stationary/books/bio4.jpeg\r\n', 6, 100, 'He came like a tidal wave, with the promise of a calm breeze. He spoke of peace, and he promised total non-cooperation. A frail old man, clad in hand-woven khadi, the British didn’t take him seriously. After all, what could one fakir do against the British Empire? In retrospect, the dramatic awe the situation inspires is too good to be true. Mohandas Karamchand Gandhi was born into a simple family. He studied to be a lawyer, was married young and loved his wife immensely. He began to realize the follies of being too beleaguered by sexual needs, and he gave up non-vegetarianism, trying meat only once. He went to London, where he studied law and hoped to be a lawyer. He journeyed to South Africa to practice, and there, outside his home, he discovered the true face of the British reign. He began to see how the coloured races were treated, and he began to fight against the regime. He returned to India, fuelled by one desire: independence. He battled the powerful British Empire with peace, nonviolence and total non-cooperation. His message of peace began to spread through the Indian people like a brushfire, and he led them in their fight for freedom. His teachings, principles and philosophy inspired them, and in return, they gave him a new name, one history would never forget: the name of Mahatma Gandhi. This is his autobiography, one of the most widely read and most detailed accounts of his life ever written.', '2021-05-24 23:24:14', 'book'),
(90, 'Biography', 'The Dhoni Touch  (English, Paperback, Sundaresan Bharat)', 299.00, 'images/stationary/books/bio5.jpeg', 6, 100, 'Be it his signature helicopter shot or his ever-calm demeanour, Mahendra Singh Dhoni has always found a way to tap into the hearts of his fans. For someone who was training to be a footballer, who could have told that Mahi was going to take the world of cricket by storm. In The Dhoni Touch: Unravelling the Enigma That Is Mahendra Singh Dhoni, Bharat Sundaresan reaches out to some of Mahi’s closest friends to find out how he became the man that he is today.', '2021-05-24 23:29:02', 'book'),
(91, 'Biography', 'Steve Jobs  (English, Paperback, Isaacson Walter)', 599.00, 'images/stationary/books/bio7.jpeg', 7, 100, 'Steve Jobs: The Exclusive Biography is based on more than forty interviews that he conducted over two years. These include discussions with more than a hundred family members, friends, adversaries, competitors, and colleagues. This book is the acclaimed, internationally best-selling biography of a business magnate, investor and co-founder of Apple Inc.', '2021-05-24 23:29:02', 'book'),
(92, 'Biography', 'Savarkar  (English, Hardcover, Sampath Vikram)', 999.00, 'images/stationary/books/bio8.jpeg', 6, 100, 'As the intellectual fountainhead of the ideology of Hindutva, which is in political ascendancy in India today, Vinayak Damodar Savarkar is undoubtedly one of the most contentious political thinkers and leaders of the twentieth century. Accounts of his eventful and stormy life have oscillated from eulogizing hagiographies to disparaging demonization. The truth, as always, lies somewhere in between and has unfortunately never been brought to light. Savarkar and his ideology stood as one of the strongest and most virulent opponents of Gandhi, his pacifist philosophy and the Indian National Congress. An alleged atheist and a staunch rationalist who opposed orthodox Hindu beliefs, encouraged inter-caste marriage and dining, and dismissed cow worship as mere superstition, Savarkar was, arguably, the most vocal political voice for the Hindu community through the entire course of India\'s freedom struggle. From the heady days of revolution and generating international support for the cause of India\'s freedom as a law student in London, Savarkar found himself arrested, unfairly tried for sedition, transported and incarcerated at the Cellular Jail, in the Andamans, for over a decade, where he underwent unimaginable torture. From being an optimistic advocate of Hindu-Muslim unity in his treatise on the 1857 War of Independence, what was it that transformed him in the Cellular Jail to a proponent of \'Hindutva\', which viewed Muslims with suspicion? Drawing from a vast range of original archival documents across India and abroad, this biography in two parts-the first focusing on the years leading up to his incarceration and eventual release from the Kalapani-puts Savarkar, his life and philosophy in a new perspective and looks at the man with all his achievements and failings.', '2021-05-24 23:50:18', 'book'),
(93, 'Biography', 'Brief Answers to the Big Questions  (English, Hardcover, Hawking Stephen)', 650.00, 'images/stationary/books/bio9.jpeg', 6, 100, 'The universe holds a lot of mysteries that are way beyond the abilities of a normal person to unravel. But, fortunately, the great mathematician and theoretical physicist, Professor Stephen Hawking has simplified some of those mysteries for us to understand. In his posthumous work, Brief Answers to the Big Questions, Stephen Hawking tries to answer some of the most frequently-asked questions, such as, “How did the universe begin?” and “Is there life beyond our solar system?”, among others.', '2021-05-24 23:50:18', 'book'),
(94, 'Biography', 'A Complete Biography of ABRAHAM LINCOLN  (English, Paperback, Lord Charnwood)', 190.00, 'images/stationary/books/bio10.jpeg', 6, 100, 'Godfrey Rathbone Benson, Ist Baron Charnwood alias Lord Charnwood (6 November 1864 - 3 February 1945) was an British author, academic, Liberal politician and philanthropist. Benson was born in Alresford, Hampshire, the son of William Benson, a barrister, and Elizabeth Soulsby Smith. He was educated at Winchester and Balliol College, Oxford. He graduated in 1887, and would later become a philosophy lecturer at Balliol. He was involved in politics and represented Woodstock in the House of Commons from 1892 to 1895 and served as Mayor of Lichfield between 1909 and 1911. The latter year Benson was raised to the peerage as Baron Charnwood, of Castle Donington in the Country of Leicester. Lord Charnwood was the author many works. These include Abraham Lincoln, which he published in 1916 as an accurate biography, and Theodore Roosevelt in 1923, another historical biography. He was also involved in charitable work with the deaf and disabled. Lord Charnwood married Dorothea Mary Roby Thorpe, daughter of Roby Thorpe, in 1897. She died in 1942. Charnwood died in London in Februrary 1945, aged 80, and was succeeded in the barony by his second but only surviving son John.', '2021-05-24 23:50:18', 'book'),
(95, 'Biography', 'IRRFAN KHAN: THE MAN, THE DREAMER, THE STAR', 350.00, 'images/stationary/books/bio11.jpeg', 6, 100, 'An actor whose eyes narrate a sea of stories. Irrfan Khan is a gentle dreamer with arresting eyes, a towering presence and an illustrious filmography. Most of us know the man only through the characters that he has played: Roohdaar in Haider, Maqbool in the eponymous film, Rana in Piku, Saajan in The Lunchbox, and of course, Ashoke in The Namesake. Today, these characters have made him a recognized name around the world. Irrfan Khan is an intimate and meticulously researched account of this refreshingly unique and unconventional Indian icon. Drawn from personal interviews and told through many voices, Aseem Chhabra traces Irrfan’s personal and artistic life in all its many shades. Rich in detail and peppered with anecdotes, it is a fascinating look at the life and work of the actor that begins in a small household in Rajasthan and culminates in his face gazing down from billboards in Hollywood. It explores some of his greatest performances that have shown India and the world what cinema can do. At the heart of this story, however, is a man, possibly the finest actor of his generation, his passion for the craft of acting and his love for unusual characters.', '2021-05-24 23:50:18', 'book'),
(96, 'Biography', 'Playing It My Way  (English, Paperback, Tendulkar Sachin)', 499.00, 'images/stationary/books/bio12.jpeg', 6, 100, 'Sachin Tendulkar’s cricket career lasted for 24 years. During this period he ruled Cricket with his brilliant batting. He never spoke much about his personal life but instead, his public dialogues were more about the game he loved the most. This autobiography that is co-authored by Boria Majumdar became an instant hit among readers and entered the Limca Book of Records for being the best-selling adult hardback across both fiction and non-fiction categories. Through this book, he talks about his journey through the world of Cricket that lasted for over two decades. He also speaks of the relationship he had with the people around him.', '2021-05-24 23:50:18', 'book'),
(97, 'Biography', 'Swami Vivekananda  (English, Paperback, Kumar Tripathi Rakesh)', 399.00, 'images/stationary/books/bio13.jpeg', 6, 100, 'Bloomsbury India', '2021-05-24 23:50:18', 'book'),
(98, 'Biography', 'A Promised Land  (English, Hardcover, Obama Barack)', 1799.00, 'images/stationary/books/bio14.jpeg', 6, 100, '\r\nTHE #1 SUNDAY TIMES BESTSELLER NAMED ONE OF THE BEST BOOKS OF THE YEAR BY The Times / Guardian / Telegraph / i News / The New York Times / Washington Post / NPR / Marie Claire A riveting, deeply personal account of history in the making-from the president who inspired us to believe in the power of democracy \'Gorgeously written, humorous, compelling, life affirming\' Justin Webb, Mail on Sunday In the stirring, highly anticipated first volume of his presidential memoirs, Barack Obama tells the story of his improbable odyssey from young man searching for his identity to leader of the free world, describing in strikingly personal detail both his political education and the landmark moments of the first term of his historic presidency-a time of dramatic transformation and turmoil. Obama takes readers on a compelling journey from his earliest political aspirations to the pivotal Iowa caucus victory that demonstrated the power of grassroots activism to the watershed night of November 4, 2008, when he was elected 44th president of the United States, becoming the first African American to hold the nation\'s highest office. Reflecting on the presidency, he offers a unique and thoughtful exploration of both the awesome reach and the limits of presidential power, as well as singular insights into the dynamics of U.S. partisan politics and international diplomacy. Obama brings readers inside the Oval Office and the White House Situation Room, and to Moscow, Cairo, Beijing, and points beyond. ', '2021-05-24 23:50:18', 'book'),
(99, 'Biography', 'Mein Kampf  (English, Hardcover, Hitler Adolf)', 699.00, 'images/stationary/books/bio16.jpeg', 6, 100, '\r\nFingerprint! Publishing', '2021-05-24 23:50:18', 'book'),
(100, 'Biography', 'Wings of Fire  (English, Paperback, Tiwari Arun)', 295.00, 'images/stationary/books/bio21.jpeg', 6, 100, 'One of the most inspiring and popular autobiographies to read is Late Abdul Kalam’s Wings of Fire. In this book, the former president shares his personal experiences and minutest details of his life. It narrates his life, right from the former late president’s rise from humble beginnings to his vision for the country in the year 2020. It has been divided into four parts equally. The first part narrates his early life that includes his parents, teachers and other influential role models. The second part deals with Kalam’s further education, work experience and his involvement with the military projects. The third and the fourth parts are about his ISRO career and the last phase of his life, where he was bestowed upon with several awards and honours. Buy Wings of Fire: An Autobiography online to read more about this great personality who played a pivotal role in shaping our country’s future.', '2021-05-24 23:50:18', 'book'),
(101, 'Biography', 'Babasaheb Ambedkar: Life and Mission :Hindi  (Hindi, Paperback, Dr. M. L. Parihar)', 250.00, 'images/stationary/books/bio22.jpeg', 6, 100, 'Babasaheb Ambedkar: Life and Mission :Hindi ,With 250 rare and original photographs', '2021-05-24 23:50:18', 'book'),
(102, 'Apple', 'Apple cover', 299.00, 'images/MOBILE/applecover1.jpg', 13, 100, 'lorem40', '2021-05-30 01:58:43', 'accessories'),
(103, 'Techno', 'Techno Spark 7(Spruce Green, 32GB)(2GB RAM)', 8999.00, 'images/MOBILE/719b6ihbwZS._SL1500_.jpg', 1, 100, '16MP AI dual rear Camera Quad Flash, 8MP Front Camera with dual front flash\r\n6000mAh powerful battery with 40 days standby\r\n6.52HD+Dot Notch Display, 20:9 wide aspect ratio\r\n2GB RAM, 32GB storage expandable up to 256GB, Dual SIM 4G+4G\r\n12 month warranty + One Time Screen Replacement for 100 days, Fast Fingerprint Sensor, Face Unlock', '2021-06-10 09:54:05', 'mobile'),
(104, 'Fiction', 'The Invisible Man (English, Paperback, Wells H. G.)', 1300.00, 'images/stationary/books/fiction11.jpeg', 7, 100, 'The Invisible Man is the story of a former medical student who devotes himself to optics and succeeds in making himself invisible. Unable to revert the process and seemingly condemned to a life of invisibility, he determines to launch a reign of terror on England.', '2021-06-12 12:57:01', 'book'),
(105, 'Fiction', 'A Game of Thrones (English, Paperback, Martin George R.R.)', 450.00, 'images/stationary/books/fiction7.jpeg', 6, 100, 'Full of adventure, mystery, intrigue, and romance, Game Of Thrones: A Song Of Ice And Fire (Book- 1) TV Tie-in Edition is a fitting opening to one of the most popular fantasy fiction series. The book contains supernatural elements which revolve around the seasons which last decades. The summer is ending and winter is fast approaching. As the cold is on its way back, it is bringing along with it deadly forces. Beyond the protective walls of the kingdom, in the frozen wastes, supernatural forces are making their way to the world of men.\r\n\r\nIn this battle for the throne, replete with death, plunder, tragedy, betrayal, terror, and treachery, two families take centre stage, the Starks and the Lannisters. Lord Eddard Stark, the newly appointed ‘Hand’ of King Robert, has to defend the Iron throne. What happens to King Robert? What does Ned Stark discover that makes him the enemy of the Queen? Will Sansa Stark marry Joffrey? Who is Daenerys Targaryen and how will her actions affect Westeros? This fantasy adventure tale, which takes place in a land of magic, dragons, and supernatural creatures, keeps readers spellbound till the very end.\r\n\r\nPublished in 1996, Game Of Thrones: A Song Of Ice And Fire (Book- 1) TV Tie-in Edition became a New York Times bestseller. The novel received the Locus Award, the Hugo Award, and the Ignotus Award. It was also nominated for the World Fantasy Award and the Nebula Award. The series was adapted into an HBO television series, which premiered in 2011.', '2021-06-12 12:57:01', 'book'),
(106, 'Literature', 'India After Gandhi (English, Paperback, Guha Ramachandra)', 700.00, 'images/stationary/books/lit1.jpeg', 7, 100, '\r\n\"Book of the Year - The Economist, Wall Street Journal, Washington Post, San Francisco Chronicle, Time Out and Outlook Winner of the Sahitya Akademi Award Ramachandra Guha’s India after Gandhi is a magisterial account of the pains, struggles, humiliations and glories of the world’s largest and least likely democracy. A riveting chronicle of the often brutal conflicts that have rocked a giant nation, and of the extraordinary individuals and institutions who held it together, it established itself as a classic when it was first published in 2007. In the last decade, India has witnessed, among other things, two general elections; the fall of the Congress and the rise of Narendra Modi; a major anti-corruption movement; more violence against women, Dalits, and religious minorities; a wave of prosperity for some but the persistence of poverty for others; comparative peace in Nagaland but greater discontent in Kashmir than ever before. This tenth anniversary edition, revised and expanded, brings the narrative up to the present. Published to coincide with seventy years of the country’s independence, this definitive history of modern India is the work of one of the world’s finest scholars at the height of his powers.\"', '2021-06-12 13:07:23', 'book'),
(107, 'Literature', 'Murder on the Orient Express (English, Paperback, Christie Agatha)', 699.00, 'images/stationary/books/lit12.jpeg', 6, 100, 'Agatha Christie\'s most famous murder mystery, reissued with a new cover to tie in with the hugely anticipated 2017 film adaptation. Just after midnight, a snowdrift stops the Orient Express in its tracks. The luxurious train is surprisingly full for the time of the year, but by the morning it is one passenger fewer. An American tycoon lies dead in his compartment, stabbed a dozen times, his door locked from the inside. Isolated and with a killer in their midst, detective Hercule Poirot must identify the murderer - in case he or she decides to strike again.', '2021-06-12 13:07:23', 'book');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `mobile`
--
ALTER TABLE `mobile`
  ADD PRIMARY KEY (`item_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `mobile`
--
ALTER TABLE `mobile`
  MODIFY `item_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=108;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
